import type { FrontendModule } from '@/types'

export const modules: FrontendModule[] = [
  {
    name: 'agents',
    label: 'Agents Monitor',
    icon: 'Monitor',
    path: '/agents',
    component: () => import('@modules/agents/page'),
  },
  {
    name: 'telemetry',
    label: 'Telemetry Hub',
    icon: 'BarChart3',
    path: '/telemetry',
    component: () => import('@modules/telemetry/page'),
  },
  {
    name: 'services',
    label: 'Services Manager',
    icon: 'Server',
    path: '/services',
    component: () => import('@modules/services/page'),
  },
  {
    name: 'factory',
    label: 'Factory',
    icon: 'Warehouse',
    path: '/factory',
    hideFromNav: true,
    component: () => import('@modules/factory/page'),
  },
  {
    name: 'commanders',
    label: 'Commanders',
    icon: 'Crown',
    path: '/commanders',
    component: () => import('@modules/commanders/page'),
  },
  {
    name: 'quests',
    label: 'Quests',
    icon: 'ClipboardCheck',
    path: '/quests',
    component: () => import('@modules/quests/page'),
  },
  {
    name: 'sentinels',
    label: 'Sentinels',
    icon: 'Clock3',
    path: '/sentinels',
    component: () => import('@modules/sentinels/page'),
  },
  {
    name: 'command-room',
    label: 'Command Room',
    icon: 'CalendarClock',
    path: '/command-room',
    component: () => import('@modules/command-room/page'),
  },
  {
    name: 'workspace',
    label: 'Workspace',
    icon: 'FolderOpen',
    path: '/workspace',
    component: () => import('@modules/workspace/page'),
  },
  {
    name: 'rpg',
    label: 'RPG',
    icon: 'Swords',
    path: '/rpg',
    component: () => import('@modules/rpg/page'),
  },
  {
    name: 'api-keys',
    label: 'Settings',
    icon: 'Settings',
    path: '/api-keys',
    component: () => import('@modules/api-keys/page'),
  },
]
